name: Deploy Project
on: [workflow_dispatch,push]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Test
        run: mvn test
      - name: Build
        run: mvn clean install
      - name: Lint
        run: |
          mvn pmd:check
          mvn verify
      - name: Deploy
        run: echo "Deploying..."

      
