name: Deploy Project
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Test
        run: mvn test

      - name: Build
        run: mvn clean install

      - name: Lint
        run: |
          mvn pmd:check
          mvn verify

      - name: Deploy
        run: echo "Deploying..."
